image: nixos/unstable
packages:
  - nixos.cachix
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
secrets:
  - f2907d38-97b4-4e7d-9fb9-57b3fb0135af
tasks:
- setup_cachix: |
    cat ~/.cachix_token | cachix authtoken --stdin
    cachix use misterio
- build: |
    cd disconic
    nix --quiet build
- upload_cachix: |
    nix path-info disconic/result/ -r | cachix push misterio
